export const AppStrings={
    welcome:'Welcome Back',
    makeChildSecure:'Lets make your child security\neasily with us',
    phoneNumber:'Phone Number',
    password:"Password",
    forgotPassword:"Forgot Password?",
    login:'Login',
    loginOptions:'or continue with',
    noAccout:'Didn\'t have an Account?',
    signUp:'Sign Up',
    helloWelcome:'Hello, Welcome',
    happyGreeting:'We are Happy to see you here!',
    cryptoName:'Enter Crypto Name',
    enterPhone:'Enter Phone Number',
    enterSafety:'Enter SafetyKey',
    reEnterSafety:'Enter SafetyKey Again',
    alreadyHaveAccount:'Already have an Account?',
    verificationCodeSent:'We have sent the verification code to your phone number',
    notYou:'Not you?',
    verify:'Verify',
    didntGotCode:'Didn\'t get any code?',
    resendAgain:'Resend Code',
    almostThere:"Almost There!\nConnect your Smartwatch\nto continue",
    connect:"Connect",
    scanQRCode:"Scan Device QR Code",
    connectGadgets:"Connect Gadgets",
    enterIMEI:"Input IMEI Number",
    viewPackage:"View Packages",
    welcomeOnly:'Welcome',
    happyToSeeYou:"We're Happy to see you!",
    gadgeDetails:"Gadget Details",
};