export const AppStrings={
    welcome:'Welcome!',
    makeChildSecure:'Lets make today Amazing!',
    phoneNumber:'Enter Phone Number',
    password:"CryptoKey",
    forgotPassword:"Forgot CryptoKey?",
    login:'Login',
    loginOptions:'or continue with',
    noAccout:'No Account?',
    signUp:'Sign Up',
    signUpHere:'Sign Up Here',
    helloWelcome:'Hello, Welcome',
    happyGreeting:'We are Happy to see you here!',
    cryptoName:'Enter CryptoName',
    enterPhone:'Enter Phone Number',
    enterSafety:'Enter SafetyKey',
    reEnterSafety:'Enter SafetyKey Again',
    alreadyHaveAccount:'Already have Account?',
    verificationCodeSent:'We have sent the verification code to your phone number',
    notYou:'Not you?',
    verify:'Verify',
    didntGotCode:'No OTP received?',
    resendAgain:'Resend again',
    almostThere:"Almost There!\nConnect your Gadget",
    connect:"Connect",
    scanQRCode:"Scan Device QR Code",
    connectGadgets:"Connect Gadgets",
    enterIMEI:"Input IMEI Number",
    viewPackage:"View Packages",
    welcomeOnly:'Welcome',
    happyToSeeYou:"We're Happy to see you!",
    gadgeDetails:"Gadget Details",
};